// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWK-POKL3AdRjaLE4yvEf6t-oTe1WOB6A',
    appId: '1:690772977631:web:6326f4ce6a6857d24b066a',
    messagingSenderId: '690772977631',
    projectId: 'nova-cabs-544fc',
    authDomain: 'nova-cabs-544fc.firebaseapp.com',
    storageBucket: 'nova-cabs-544fc.firebasestorage.app',
    measurementId: 'G-7GX0DLKL8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSVyyvVwGcSDzNnuDRK9h5YR5U7Hz2lVw',
    appId: '1:690772977631:android:ddb59fad796fe9c04b066a',
    messagingSenderId: '690772977631',
    projectId: 'nova-cabs-544fc',
    storageBucket: 'nova-cabs-544fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSFWpD8baacd_De2xdtStmlJeMp41DKKY',
    appId: '1:690772977631:ios:b7aaa93a232a256b4b066a',
    messagingSenderId: '690772977631',
    projectId: 'nova-cabs-544fc',
    storageBucket: 'nova-cabs-544fc.firebasestorage.app',
    iosBundleId: 'com.example.novaCabs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWK-POKL3AdRjaLE4yvEf6t-oTe1WOB6A',
    appId: '1:690772977631:web:88f07601cb8826d44b066a',
    messagingSenderId: '690772977631',
    projectId: 'nova-cabs-544fc',
    authDomain: 'nova-cabs-544fc.firebaseapp.com',
    storageBucket: 'nova-cabs-544fc.firebasestorage.app',
    measurementId: 'G-M6C6HRZ4YR',
  );
}
